# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

# CI::Reporter RSpec task
require 'ci/reporter/rake/cucumber'

task :cucumber => 'ci:setup:cucumber'


Rails.application.load_tasks
